//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DependencyStudio.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_DEPENDENCYSTUDIOAPP_DIALOG  102
#define IDD_DEPENDENCYSTUDIO_DIALOG     102
#define IDS_DEPENDENCYSTUDIO            102
#define IDS_LOGOFF                      103
#define IDD_TESTPAGE                    103
#define IDS_QUIT                        104
#define IDS_CHANGE_PASSWORD             105
#define IDS_INFO                        106
#define IDS_DEPENDENCYSTUDIO_RUNS       107
#define IDS_DEPENDENCYSTUDIO_RUNS_CONT  108
#define IDS_DEPENDENCYSTUDIO_RUNS_CONT1 108
#define IDS_NOT_LOGGED_IN               108
#define IDS_AUTOSTART                   109
#define IDS_ERROR                       110
#define IDS_ACTIVEAPPS                  111
#define IDS_APPS_WILL_FINISHED          112
#define IDS_NOT_FINISHED                113
#define IDS_CACHE_MODE                  114
#define IDS_AUTARK_MODE                 115
#define IDS_CACHE_DB_CRASHED            116
#define IDS_NORMAL_MODE                 117
#define IDS_DIRECT_MODE                 118
#define IDS_MERGE_MODE                  119
#define IDS_NO_SUSPEND                  120
#define IDS_NO_STANDBY                  121
#define IDS_LOGGED_IN_AS                122
#define IDS_HUPTV_NOFUNC                123
#define IDS_HUPTV_NOPROCESS             124
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       129
#define IDB_TSGDEPENDENCYSTUDIO         131
#define IDB_MPODEPENDENCYSTUDIO         131
#define IDR_MENU_HILFE                  132
#define IDR_DEPENDENCYSTUDIO_MENU       132
#define IDB_DEPENDENCYSTUDIOTEXT        135
#define IDB_STATUS1                     137
#define IDB_STATUS3                     138
#define IDB_STATUS2                     139
#define IDB_STATUS4                     140
#define IDB_HENKELOGO                   143
#define IDB_HENKEDEPENDENCYSTUDIO       144
#define IDS_CREATEDB_OVERWRITE          152
#define IDS_CREATEDB                    153
#define IDS_CREATEDB_PROGRESSDLGTITLE   154
#define IDS_CREATEDB_PROCESSINGMODULE   155
#define IDS_CREATEDB_DONECOUNT          156
#define IDR_MENU1                       156
#define IDR_MENU_POPUP                  156
#define IDS_UNSAVED_CHANGES             157
#define IDB_CANCELFILTER                158
#define IDS_SAVE_BEFORE_CLOSE           158
#define IDS_TITLE_PLAIN                 159
#define IDS_TITLE_LOADED                160
#define IDI_LOGO_SMALL                  160
#define IDS_QUERY_PARAM_GROUP_TITLE     161
#define IDS_RELOAD_DATABASE             162
#define IDS_WARNING                     163
#define IDS_ABOUT_TEXT                  164
#define IDS_ABOUT                       165
#define IDC_EDIT_QUERY                  1004
#define IDC_CHECK_ONLYWORDS             1006
#define IDC_CHECK_MODULENAMES           1014
#define IDC_CHECK_EXPORTS               1015
#define IDC_TREE_SUBJECTS               1016
#define IDC_TAB_RESULTS                 1017
#define IDC_TREE_RESULTS                1020
#define IDC_CHECK_CASESENSITIVE         1027
#define IDC_RICHEDIT_FILTER             1029
#define IDC_BUTTON_SPLITTER             1032
#define IDC_BUTTON_CANCELFILTER         1036
#define IDC_GROUP_QUERY                 1037
#define IDC_GROUP_FILTER                1038
#define IDC_BUTTON_SELECTALL            1040
#define IDC_BUTTON_SELECTNONE           1041
#define IDC_BUTTON_UPDATE               1042
#define IDC_BUTTON1                     1046
#define IDC_BUTTON_SEARCH               1046
#define IDC_STATIC_FILTER               1047
#define IDC_CHECK1                      1048
#define IDC_CHECK_RECURSIVE             1048
#define IDC_GROUP_SEARCH_PARAMS         1049
#define IDC_SPLITTER                    1051
#define IDC_TREE_LEFT                   1052
#define IDC_TREE_RIGHT                  1053
#define ID_ALLOCDYNAMICMAX              32773
#define ID_DATENBANK_LADEN              32778
#define ID_DATENBANK_ZULETZTGE32779     32779
#define ID_DATENBANK_SPEICHERN          32780
#define ID_DATENBANK_SCHLIE32781        32781
#define ID_MODUL_PATCHTESTEN            32782
#define ID_MODUL_HINZUF32783            32783
#define ID_MODUL_ENTFERNEN              32784
#define ID_MODUL_AKTUALISIEREN          32785
#define ID_MODUL_PATCHEINSPIELEN        32786
#define ID_ANSICHT_ALSHTMLSPEICHERN     32787
#define ID_ANSICHT_ALS                  32788
#define ID_ABFRAGE_AKTUALISIEREN        32789
#define ID_ANSICHT_DUPLIZIEREN          32790
#define ID_ANSICHT_SCHLIE32791          32791
#define ID_ABFRAGE_AKTUALISIEREN32792   32792
#define ID_ABFRAGE_NEU                  32793
#define ID_ANSICHT_NEU                  32794
#define ID_ABFRAGE_DUPLIZIEREN          32795
#define ID_ABFRAGE_SCHLIE32796          32796
#define ID_ABFRAGE_ZUR32797             32797
#define ID_ABFRAGE_VORW32798            32798
#define ID_HILFE_ABOUT                  32799
#define ID_LOAD_DATABASE                32800
#define ID_RECENT_DATABASES             32801
#define ID_SAVE_DATABASE                32802
#define ID_CLOSE_DATABASE               32803
#define ID_ZULETZTGE32804               32804
#define ID_ANSICHT                      32805
#define ID_DATABASE                     32806
#define ID_MODULE                       32807
#define ID_DATENBANK_SPEICHERNUNTER     32808
#define ID_HILFE_BENUTZERHILFE          32809
#define ID_USERHELP                     32810
#define ID_ABOUT                        32811
#define ID_RESULT_EXPORT                32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
